version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Nuxt.js 앱 포트
    env_file:
      - .env
    volumes:
      - shared-data:/shared
    restart: always

  reloader:
    build:
      context: ./reloader
    ports:
      - "5050:5050"  # FastAPI 웹훅 수신 포트
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 소켓을 마운트하여 Docker 컨테이너를 제어할 수 있게 함
      - shared-data:/shared
    env_file:
      - .env
    depends_on:
      - frontend  # frontend 서비스가 실행된 후 시작
    restart: always

volumes:
  shared-data: